
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.


# Examples of 5 Numpy array Functions to show variety of oprations possible with NumPy



NumPy is a fast maths library for Python with a heavy emphasis on arrays. It allows you to do vector and matrix maths within Python and as a lot of the underlying functions that are actually written in C++.

- det(A)
- shape(a)
- inv(a)
- swapaxes(a,axis1, axis2)
- split(ary, indices_or_sections[, axis])

1. det  : is used for finding the determinant of Matrix A 
2. shape : Return the shape of an array.
3. inv : Compute the (multiplicative) inverse of a matrix.
4. swapaxes : interchange two axes of an array.
5. Split : Split an array into multiple sub-arrays as views into array.
The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [4]:
!pip install jovian --upgrade -q

In [5]:
import jovian

In [6]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "polaris-codev/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/polaris-codev/numpy-array-operations


'https://jovian.ai/polaris-codev/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [11]:
# List of functions explained 
# function1 = np.linalg.det()  
# function2 = np.shape()
# function3 = np.inv()
# function4 = np.swapaxes()
# function5 = np.split()

## Function 1 - det method
It is used for finding the determinant of a Matrix .

In [32]:
# Example 1 : - Working case 1
arr1 =np.array([[1, 2,3], [3, 4,5], [5,6,7]])
i = np.linalg.det(arr1)
print(i)

0.0


Explanation about example

In [33]:
# Example 2 : working case 2

arr2 = np.array([[5, 3, 7],[8, 1, 10],[11,2,13]])
j = np.linalg.det(arr2)
print(j)

17.999999999999996


Here the determinant function fails as it requires a square matrix

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 =np.array([[5, 6, 7], [8, 9, 10]])
k = np.linalg.det(arr3)
print(k)

LinAlgError: Last 2 dimensions of the array must be square

Determinant is only possible for square matrices. We will have to be careful when giving input.

In [11]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "polaris-codev/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/polaris-codev/numpy-array-operations


'https://jovian.ai/polaris-codev/numpy-array-operations'

## Function 2 - Shape method

Return the shape of an array.

In [35]:
# Example 1 - working
arr4 = np.array([[1,2,3],[4,3,2]])
np.shape(arr4)

(2, 3)

Here it returns the dimensions of the matrix "arr4" which is (2,3)

In [36]:
# Example 2 - working
arr5 = np.array([[3,4,5,6],[2,3,2,1],[4,5,6,3]])
np.shape(arr5)

(3, 4)

Similar to previous example it returns dimension of matrix arr5 that is (3,4)

In [37]:
# Example 3 - breaking (to illustrate when it breaks)
arr6 = np.array([[2,3],[2,1,4],[4,3]])
np.shape(arr6)

/tmp/ipykernel_35/105035093.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr6 = np.array([[2,3],[2,1,4],[4,3]])


(3,)

Here the error is due to no having proper dimensions in arr6. The matrix must have same number of elements in rows which is not so in first row, hence the error

We must properly check while giving input to shape method as it is the most common problem faced by many people while using shape method

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "polaris-codev/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/polaris-codev/numpy-array-operations


'https://jovian.ai/polaris-codev/numpy-array-operations'

## Function 3 - Inverse Method

It gives the inverse of a matrix i.e. when a matrix and its inverse is multiplied it results in identity matrix

In [38]:
# Example 1 - working
arr7 = np.array([[1,2,3],[3,2,1],[4,3,1]])
np.linalg.inv(arr7)

array([[-0.25,  1.75, -1.  ],
       [ 0.25, -2.75,  2.  ],
       [ 0.25,  1.25, -1.  ]])

here the output given is the inverse of matrix arr7

In [39]:
# Example 2 - working
arr8 = np.array([[6,7],[2,3]])
np.linalg.inv(arr8)

array([[ 0.75, -1.75],
       [-0.5 ,  1.5 ]])

Similarly it shows inverse of matrix arr8

In [40]:
# Example 3 - breaking (to illustrate when it breaks)
arr9 = np.array([[2,3,4],[1,2,5]])
np.linalg.inv(arr9)

LinAlgError: Last 2 dimensions of the array must be square

Here the reason for an error is that for finding a matrix's inverse, it must be a square matrix i.e. same same number of rows and columns.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Function 4 - swapaxes method

It is used to swap the axes of the matrix.

In [9]:
# Example 1 - working
arr10 = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
np.swapaxes(arr10,0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

Here the matrix arr10 is swapped across its axes

In [16]:
# Example 2 - working
arr11 = np.array([[1,2,3]])
np.swapaxes(arr11,0,1)

array([[1],
       [2],
       [3]])

Similar to previous example arr11 is swapped across its axes

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
arr12 = np.array([[1,2,3],[4,3,2],[5,6,7]])
np.swapaxes(arr12,1,2)

AxisError: axis2: axis 2 is out of bounds for array of dimension 2

Here the error is due to a 2-Dimensional array having only 2 axes, therefore using 2 in axes which corresponds to third axes shows out-of-bounds error. If it was doing this operation on a 3D arrays it will not show this error.

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "polaris-codev/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/polaris-codev/numpy-array-operations


'https://jovian.ai/polaris-codev/numpy-array-operations'

## Function 5 - Split Method

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [23]:
# Example 1 - working
arr13= np.arange(9.0)
np.split(arr13, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

Here arr13 having 0 to 9 numbers is splitted into 3 arrays having 3 elements each.

In [27]:
# Example 2 - working
arr14 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
np.split(arr14, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

Here is Splitting the 2-D array into three 2-D arrays along rows.

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
arr15 = np.array([2,3,5,6])
np.split(arr15,3)

ValueError: array split does not result in an equal division

Here the error is due to indices_or_sections given as an integer, but a split does not result in equal division. As 4 elements can't be divided into 3 equal parts.

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "polaris-codev/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/polaris-codev/numpy-array-operations


'https://jovian.ai/polaris-codev/numpy-array-operations'

## Conclusion

In this notebook I covered just a small fraction i.e. only five Linear Algebra functions which NumPy has to offer. There are tons of functions available on the NumPy documentation page. It is really amazing to see so many functions available for us to use and make our life so much easy. Refer to it and make it one of your best friends!

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>